spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loginlearning?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
  type-aliases-package: com.ruibin.loginlearning.pojo
